### ISSUE TITLE
Automatically set color based on some conditions

### ISSUE THREAD

**Issue by JReinhold** [bernardop/iterm-tab-color-oh-my-zsh#1]
This project is actually a brilliant idea. 👍
However I think that it would be incredibly more useful, if we could automatically set tab colors based on different stuff that is happening within the tab.

The use case I'm thinking of, is when I have multiple tabs open, the colorization would make them easily scannable. Possible conditions:

- **Set color whenever the cwd is a specified directory**. Eg. all my blue tabs are my open-source development tabs, while all my green tabs are my work related development.
- **Set color based on current running job** - Eg. `yarn test` sets the color to white, `yarn start` is green, `docker-compose up` is red, etc.
- **Set color based on last command exit code** - Eg. I ran a command that exited with an error, therefore set the tab to a red color.

(I noticed a similar discussion in your tweet, I just wanted to jot this down quickly). 🙂

Good job!

**Comment by dmacompton** [comment]
@JReinhold thanks you for your idea of adding colors to tab by running process.
I've created couple alias for bash which runs process & apply colors)
not the best solution but it works for me 😄 

```
function goToEvents() {
    cd /Users/dmacompton/server/events-frontend
    tc $1
    npm run $2
    if ($3)
      tc $3
}

alias events="goToEvents 297ad1 start"
alias tests="goToEvents a53b4e test 3ed411"
alias lint="goToEvents 5327ca eslint 3ed411"

**Comment by bernardop** [comment]
@JReinhold Thanks!

Like I mentioned on that twitter conversation you refer to, I don't have a lot of experience with bash/zsh programming haha, however I'm looking at some [hooks](http://zsh.sourceforge.net/Doc/Release/Functions.html#Hook-Functions) that I can use in zsh to accomplish some of the things you propose. For starters I'll play around with trying to set tab colors based on the cwd.

**Comment by bernardop** [comment]
@JReinhold I updated the project to change colors based on your current working directory. There's a new file where you can specify which directories correspond to which tab colors. If I have some time later I'll try to tackle the colors based on current running process.

**Comment by JReinhold** [comment]
Oh wow, that is so cool. works like a charm, thanks! 😃
